name: Remote Action

on:
  push:
    branches:
      - main

jobs:
  remote_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Server Host Key
        run: ssh-keyscan -H 3.81.102.212 >> ~/.ssh/known_hosts

      - name: Run Remote Command
        run: ssh ubuntu@3.81.102.212 "echo 'Hello from GitHub Workflow' > ~/workflow_output.txt"
